# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(first_name: "Sebastien", 
			last_name: "Thomas", 
			email: "titbabthomas@gmail.com", 
			address: "10314 Strathmore Hall Street Apt 203, North Bethesda, MD 20852",
			password: "admin123", 
			password_confirmation: "admin123", 
			admin:true)

User.create(first_name: "Samantha", last_name: "Louis", email: "samanthalouis.12@gmail.com", address: "1611 Pine Street, New Orleans, LA 70118", password: "admin123", password_confirmation: "admin123", admin:true)
User.create(first_name: "Deco", last_name: "Adrien", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Lolo", last_name: "Adrien", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Lottie", last_name: "Adrien", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Paul", last_name: "Adrien", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Valou", last_name: "Adrien", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Altagrace", last_name: "Allen", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Cedric", last_name: "Almonacy", email: "", address: "8 Victoria ave. Cranston RI 02920", password: "password", password_confirmation: "password")
User.create(first_name: "Pascale", last_name: "Almonacy", email: "", address: "8 Victoria ave. Cranston RI 02920", password: "password", password_confirmation: "password")
User.create(first_name: "Reginald", last_name: "Almonacy", email: "", address: "8 Victoria ave. Cranston RI 02920", password: "password", password_confirmation: "password")
User.create(first_name: "Tarah", last_name: "Almonacy", email: "", address: "8 Victoria ave. Cranston RI 02920", password: "password", password_confirmation: "password")
User.create(first_name: "Tessah", last_name: "Almonacy", email: "", address: "8 Victoria ave. Cranston RI 02920", password: "password", password_confirmation: "password")
User.create(first_name: "Fabiola", last_name: "Alouidor", email: "", address: "210 Millbrook Dr. East Longmeadow MA 01028", password: "password", password_confirmation: "password")
User.create(first_name: "Elsie", last_name: "Altenar", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Ted", last_name: "Altenar", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Elisabeth", last_name: "Anantua", email: "", address: "63 Glenmalure St Amityville, NY 11701", password: "password", password_confirmation: "password")
User.create(first_name: "Leo", last_name: "Anantua", email: "", address: "63 Glenmalure St Amityville, NY 11701", password: "password", password_confirmation: "password")
User.create(first_name: "Ricky", last_name: "Anantua", email: "", address: "63 Glenmalure St Amityville, NY 11701", password: "password", password_confirmation: "password")
User.create(first_name: "Claudine", last_name: "Andre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Dimitri", last_name: "Andre", email: "", address: "56 Jordan Avenue 3R, Jersey City, NJ 07306", password: "password", password_confirmation: "password")
User.create(first_name: "Dominique", last_name: "Andre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Donat", last_name: "Andre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Gertrude", last_name: "Andre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Kristie", last_name: "Barthelemy", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Catherine", last_name: "Beauboeuf", email: "", address: "2 South Leavitt St unit 410, Chicago, Il 60612", password: "password", password_confirmation: "password")
User.create(first_name: "Shanna", last_name: "Beauge", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Dupuis", last_name: "Bernado", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Soraya", last_name: "Blot", email: "", address: "2867 Yonge Street Apt 2 Toronto ON M4N 2J5, Canada", password: "password", password_confirmation: "password")
User.create(first_name: "Gary", last_name: "Brice", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Marthe", last_name: "Brice", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Stephan", last_name: "Brice", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Taina", last_name: "Brice", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Adrienne", last_name: "Bus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Carl-Henry", last_name: "Caidor", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Carol", last_name: "Caidor", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Genevieve", last_name: "Caidor", email: "", address: "14 Sterling Rd, Elmont, NY 11003", password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Marie", last_name: "Caidor", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Marie Jr", last_name: "Caidor", email: "", address: "14 Sterling Rd, Elmont, NY 11003", password: "password", password_confirmation: "password")
User.create(first_name: "Joan", last_name: "Caidor", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "David", last_name: "Calixte", email: "", address: "4702 Lake Park Pl, Acworth, GA 30101", password: "password", password_confirmation: "password")
User.create(first_name: "Charles", last_name: "Carrenard", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Christian", last_name: "Carrenard", email: "", address: "1137 E 100 St, Brooklyn NY 11236", password: "password", password_confirmation: "password")
User.create(first_name: "Germaine", last_name: "Carrenard", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Herve", last_name: "Carrenard", email: "", address: "1137 E 100 St, Brooklyn NY 11236", password: "password", password_confirmation: "password")
User.create(first_name: "Sylvie", last_name: "Carrenard", email: "", address: "1137 E 100 St, Brooklyn NY 11236", password: "password", password_confirmation: "password")
User.create(first_name: "Tatianna", last_name: "Carrenard", email: "", address: "1137 E 100 St, Brooklyn NY 11236", password: "password", password_confirmation: "password")
User.create(first_name: "Jacoune", last_name: "Cayenne", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Minou", last_name: "Cayenne", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Pere Dume", last_name: "Cayenne", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Pere Jude", last_name: "Cayenne", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Pere Reginal", last_name: "Cayenne", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Jethro", last_name: "Celestin", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Dr. Marjorie", last_name: "Charles", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Dabel", last_name: "Dabel", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "darline", last_name: "Darline", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Alyn", last_name: "Defay", email: "", address: "115-71 223rd st Cambria heights, NY 11411", password: "password", password_confirmation: "password")
User.create(first_name: "Fabrice", last_name: "Defay", email: "", address: "115-71 223rd st Cambria heights, NY 11411", password: "password", password_confirmation: "password")
User.create(first_name: "Jennifer", last_name: "Desir", email: "", address: "480 NW 20th St. Apt 202. Boca Raton, Fl 33431", password: "password", password_confirmation: "password")
User.create(first_name: "Metive", last_name: "Dieudonne", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Frances", last_name: "Dormethus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Martine", last_name: "Dormethus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Chrissie", last_name: "Dornevil", email: "", address: "2780 Austin Ridge Drive, Dacula, Ga 30019", password: "password", password_confirmation: "password")
User.create(first_name: "Alexa", last_name: "Dubois", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Paul", last_name: "Duperval", email: "", address: "93 Soundview Ave Bridgeport, CT 06606", password: "password", password_confirmation: "password")
User.create(first_name: "Craig", last_name: "EUHHH", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Anne-Carine", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Arthur", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Bertrand", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Christian", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Claudine", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Matthieu", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Melissa", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Mireille", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Olivier", last_name: "Exume", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Christel", last_name: "Fenelon", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Aurelie", last_name: "Fievre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Louckendia", last_name: "Francois", email: "", address: "260 Rue Gamelin, Repentigny, QC J6A 5V1, Canada", password: "password", password_confirmation: "password")
User.create(first_name: "Alfredo", last_name: "Frederique", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Cluvia", last_name: "Frederique", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Fred", last_name: "Frederique", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Lola", last_name: "Frederique", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Toto", last_name: "Frederique", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Roudy", last_name: "Gerlus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Gigi", last_name: "Gigi", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "David", last_name: "Gonzales", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Dayana", last_name: "Gonzales", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Mon oncle Napo", last_name: "Guadeloupe", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Patrick", last_name: "Guadeloupe", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Sylvie", last_name: "Guadeloupe", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Luc", last_name: "Hamilton", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "parrain de Seby", last_name: "Hilaire", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Christina", last_name: "Jean", email: "", address: "1896 NW 145th Terrace, Pembroke Pines, FL 33028", password: "password", password_confirmation: "password")
User.create(first_name: "Vicenta", last_name: "Jean Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Yadine", last_name: "Jean Jacques", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Alta", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Bonel", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Carmelle", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Elza", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Ezebre", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Frenie", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Guerrier", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Hirame", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Joanna", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Joey", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Luco", last_name: "Jean-Baptiste", email: "", address: "2823 Oswego Street, North Bellmore, NY 11710", password: "password", password_confirmation: "password")
User.create(first_name: "Marcus", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Marie", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Marinelle", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Nathalie", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Pashoue", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Roro", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Stephanie", last_name: "Jean-Baptiste", email: "", address: "19 Wyndham Court Nanuet, NY 10954", password: "password", password_confirmation: "password")
User.create(first_name: "Vladimir", last_name: "Jean-Baptiste", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Anne-Marie", last_name: "Jean-Lor", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Madan Pino", last_name: "Jean-Louis", email: "", address: "239 East 51St #3 Brooklyn NY 11203", password: "password", password_confirmation: "password")
User.create(first_name: "Pino", last_name: "Jean-Louis", email: "", address: "239 East 51St #3 Brooklyn NY 11203", password: "password", password_confirmation: "password")
User.create(first_name: "Stephane", last_name: "Jean-Pierre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Claude", last_name: "Jean-Poix", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Nicole", last_name: "Jean-Poix", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Rene", last_name: "Joseph", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Ti Maude", last_name: "Kill", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Olguin", last_name: "Laroche", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Christiane", last_name: "Lecorps", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Ermond", last_name: "Lecorps", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Joujou", last_name: "Lecorps", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Myriam", last_name: "Lecorps", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Nath", last_name: "Lecorps", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Natalie", last_name: "Lemaine", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Robert", last_name: "Lemaine", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Leslie", last_name: "Leslie", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Emmanuelle", last_name: "Louis", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Sarah", last_name: "Louis", email: "", address: "4707 Ave L, Brooklyn, NY 11234", password: "password", password_confirmation: "password")
User.create(first_name: "Sebastien", last_name: "Louis", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Serge", last_name: "Louis", email: "", address: "Rue Alfred Laurence Apt 4 #11615, Montreal, QC H1E 3L6", password: "password", password_confirmation: "password")
User.create(first_name: "Sergine", last_name: "Louis", email: "", address: "4707 Ave L, Brooklyn, NY 11234", password: "password", password_confirmation: "password")
User.create(first_name: "Stephanie", last_name: "Louis", email: "", address: "4707 Ave L, Brooklyn, NY 11234", password: "password", password_confirmation: "password")
User.create(first_name: "Tarah", last_name: "Louis", email: "", address: "1373 Rue du Relais, Laval, QC H7Y 1W2, Canada", password: "password", password_confirmation: "password")
User.create(first_name: "Thiery", last_name: "Louis", email: "", address: "4707 Ave L, Brooklyn, NY 11234", password: "password", password_confirmation: "password")
User.create(first_name: "Eunide", last_name: "Ma marraine", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Hilaire", last_name: "Maisonneuve", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Kendia", last_name: "Maisonneuve", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Elliot Desruisseaux", last_name: "Maitre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Femme", last_name: "Maitre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Regine", last_name: "Manmie", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Thom", last_name: "Manmie", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Mme Abner", last_name: "Marc", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Mononcle Abner", last_name: "Marc", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Jean", last_name: "Marcelin", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Miquette", last_name: "Marcelin", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Claude", last_name: "Massena", email: "", address: "146 -19th 227th Street Springfield gardens NY 11413", password: "password", password_confirmation: "password")
User.create(first_name: "KArina", last_name: "Massena", email: "", address: "146 -19th 227th Street Springfield gardens NY 11413", password: "password", password_confirmation: "password")
User.create(first_name: "Patricia", last_name: "Massena", email: "", address: "146 -19th 227th Street Springfield gardens NY 11413", password: "password", password_confirmation: "password")
User.create(first_name: "Cassandre", last_name: "Merger", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Lucita", last_name: "Merger", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Sergio", last_name: "Merger", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Pascal", last_name: "Merveille", email: "", address: "4250 Alafaya Trail Suite 212-250, Oviedo, FL 32765", password: "password", password_confirmation: "password")
User.create(first_name: "Gregory", last_name: "Michel", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Zebledlo", last_name: "Michel", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Margareth", last_name: "Mon parrain", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Mon parrain", last_name: "Mon parrain", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Frederique", last_name: "Montas", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Kimberly", last_name: "Ncolas", email: "", address: "740 G St, Lincoln NE 68508", password: "password", password_confirmation: "password")
User.create(first_name: "Canes", last_name: "Nicolas", email: "", address: "740 G St, Lincoln NE 68508", password: "password", password_confirmation: "password")
User.create(first_name: "Kristel", last_name: "Paul", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Pablo", last_name: "Paul", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Carlos", last_name: "Pereryra", email: "", address: "8 Perimeter Ctr. E. 2319 Atlanta, GA 30346", password: "password", password_confirmation: "password")
User.create(first_name: "Charissa", last_name: "Pierre", email: "", address: "3450 Jones Mill Rd #520, Norcross, GA 30092", password: "password", password_confirmation: "password")
User.create(first_name: "Fabienne", last_name: "Pierre", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Alain", last_name: "Pierre-Pierre", email: "", address: "144-44 41st ave, Apt 1h, Flushing NY 11355", password: "password", password_confirmation: "password")
User.create(first_name: "Linda", last_name: "Pierrot", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Georgette", last_name: "Remy", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Paulette", last_name: "Rochefort", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Rochefort", last_name: "Rochefort", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Maria", last_name: "Roy", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Clemene", last_name: "Semenran", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Agla", last_name: "Senatus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Alain", last_name: "Senatus", email: "", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1", password: "password", password_confirmation: "password")
User.create(first_name: "Dorothy", last_name: "Senatus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Fabrice", last_name: "Senatus", email: "", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1", password: "password", password_confirmation: "password")
User.create(first_name: "Larissa", last_name: "Senatus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Luc", last_name: "Senatus", email: "", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1", password: "password", password_confirmation: "password")
User.create(first_name: "Mycotte", last_name: "Senatus", email: "", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1", password: "password", password_confirmation: "password")
User.create(first_name: "Myriam", last_name: "Senatus", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Reyina", last_name: "Senatus", email: "", address: "419 Towerview Drive - Box 98893, Edens 1A - Room 403, Durham, NC 27708", password: "password", password_confirmation: "password")
User.create(first_name: "Ronald", last_name: "Senatus", email: "", address: "2111 Branywine Rd Apt 913, West Palm beach FL 33409", password: "password", password_confirmation: "password")
User.create(first_name: "Arabel", last_name: "Severe", email: "", address: "5332 Rpcking Horse Place Oviedo FL 32765", password: "password", password_confirmation: "password")
User.create(first_name: "Chanel", last_name: "Smith", email: "", address: "P.O. Box 881411, San Diego, California 92168", password: "password", password_confirmation: "password")
User.create(first_name: "Altagrace", last_name: "Soeur", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Flor", last_name: "Soeur", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Franklin", last_name: "St-Surin", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Hans-Muller", last_name: "Thomas", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Kervens", last_name: "Thomas", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Nadine", last_name: "Thomas", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Sarah", last_name: "Thomas", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Tibel", last_name: "Tibel", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Navneet", last_name: "Tiwari", email: "", address: "425 Washingtn BLV Apt 3308 Jersey City NY07310", password: "password", password_confirmation: "password")
User.create(first_name: "Francois", last_name: "Andre", email: "", address: "397 East 7 St, Brooklyn, NY 11218", password: "password", password_confirmation: "password")
User.create(first_name: "Ernst", last_name: "Toussaint", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Hilaire", last_name: "Toussaint", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Janette", last_name: "Toussaint", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Gheriane", last_name: "Ulysse", email: "", address: "247 Crystal Downs Way, Suwanee GA 30024", password: "password", password_confirmation: "password")
User.create(first_name: "Andy", last_name: "Valles", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Aurelie", last_name: "Valles", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Cassandra", last_name: "Valles", email: "", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada", password: "password", password_confirmation: "password")
User.create(first_name: "Chantale", last_name: "Valles", email: "", address: "1746 Woodwalk Creek, Atlanta, GA, 30339", password: "password", password_confirmation: "password")
User.create(first_name: "Dominique", last_name: "Valles", email: "", address: "2272 Norbury Dr, Smyrna, GA 30080", password: "password", password_confirmation: "password")
User.create(first_name: "Eunide", last_name: "Valles", email: "", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada", password: "password", password_confirmation: "password")
User.create(first_name: "Gaelle", last_name: "Valles", email: "", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada", password: "password", password_confirmation: "password")
User.create(first_name: "Jude", last_name: "Valles", email: "", address: "2272 Norbury Dr, Smyrna, GA 30080", password: "password", password_confirmation: "password")
User.create(first_name: "Lionel", last_name: "Valles", email: "", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada", password: "password", password_confirmation: "password")
User.create(first_name: "Nadege", last_name: "Valles", email: "", address: "2272 Norbury Dr, Smyrna, GA 30080", password: "password", password_confirmation: "password")
User.create(first_name: "Phillip", last_name: "Valles", email: "", address: "2272 Norbury Dr, Smyrna, GA 30080", password: "password", password_confirmation: "password")
User.create(first_name: "Annaise", last_name: "Verret", email: "", address: "4250 Alafaya Trail Suite 212-250, Oviedo, FL 32765", password: "password", password_confirmation: "password")
User.create(first_name: "Ericson", last_name: "Vibert", email: "", address: "1049 powers ferry rd apt 203 Marietta GA 30067", password: "password", password_confirmation: "password")
User.create(first_name: "Joanne", last_name: "Voisine", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Katie", last_name: "Weander", email: "", address: "17734 Castelar Cir, Omaha NE 6810", password: "password", password_confirmation: "password")
User.create(first_name: "Femme", last_name: "Wesner", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Marc", last_name: "Wesner", email: "", address: "", password: "password", password_confirmation: "password")
User.create(first_name: "Bugra", last_name: "Yavuz", email: "", address: "", password: "password", password_confirmation: "password")

#49.times do |n|
#  first_name  = Faker::Name.first_name
#  last_name  = Faker::Name.last_name
#  email = "example-#{n+1}@dummy.org"
#  password = "password"
#  User.create!(first_name:  first_name,
#  			   last_name:  last_name,
#               email: email,
#               password: password,
#               password_confirmation: password)
#end