# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(first_name: "Sebastien", 
			last_name: "Thomas", 
			email: "titbabthomas@gmail.com", 
			address: "10314 Strathmore Hall Street Apt 203, North Bethesda, MD 20852",
			password: "admin123", 
			password_confirmation: "admin123", 
			admin:true)
			
User.create(first_name: "Samantha", 
			last_name: "Louis", 
			email: "samanthalouis.12@gmail.com", 
			address: "1611 Pine St, New Orleans, LA 70118",
			password: "admin123", 
			password_confirmation: "admin123", 
			admin:true)

User.create(first_name: "Deco", last_name: "Adrien",password: "password", password_confirmation: "password")
User.create(first_name: "Lolo", last_name: "Adrien",password: "password", password_confirmation: "password")
User.create(first_name: "Lottie", last_name: "Adrien",password: "password", password_confirmation: "password")
User.create(first_name: "Paul", last_name: "Adrien",password: "password", password_confirmation: "password")
User.create(first_name: "Valou", last_name: "Adrien",password: "password", password_confirmation: "password")
User.create(first_name: "Altagrace", last_name: "Allen",password: "password", password_confirmation: "password")
User.create(first_name: "Cedric", last_name: "Almonacy",password: "password", password_confirmation: "password", email: "pembrokeal@hotmail.com", address: "8 Victoria ave. Cranston RI 02920")
User.create(first_name: "Pascale", last_name: "Almonacy",password: "password", password_confirmation: "password", email: "thomaspascale@hotmail.com", address: "8 Victoria ave. Cranston RI 02920")
User.create(first_name: "Reginald", last_name: "Almonacy",password: "password", password_confirmation: "password", email: "capoisal@hotmail.com", address: "8 Victoria ave. Cranston RI 02920")
User.create(first_name: "Tarah", last_name: "Almonacy",password: "password", password_confirmation: "password", address: "8 Victoria ave. Cranston RI 02920")
User.create(first_name: "Tessah", last_name: "Almonacy",password: "password", password_confirmation: "password", address: "8 Victoria ave. Cranston RI 02920")
User.create(first_name: "Fabiola", last_name: "Alouidor",password: "password", password_confirmation: "password", address: "210 Millbrook Dr. East Longmeadow MA 01028")
User.create(first_name: "Elsie", last_name: "Altenar",password: "password", password_confirmation: "password")
User.create(first_name: "Ted", last_name: "Altenar",password: "password", password_confirmation: "password")
User.create(first_name: "Elisabeth", last_name: "Anantua",password: "password", password_confirmation: "password", email: "listhomas09@yahoo.com", address: "63 Glenmalure St Amityville, NY 11701")
User.create(first_name: "Leo", last_name: "Anantua",password: "password", password_confirmation: "password", address: "63 Glenmalure St Amityville, NY 11701")
User.create(first_name: "Ricky", last_name: "Anantua",password: "password", password_confirmation: "password", address: "63 Glenmalure St Amityville, NY 11701")
User.create(first_name: "Claudine", last_name: "Andre",password: "password", password_confirmation: "password")
User.create(first_name: "Dimitri", last_name: "Andre",password: "password", password_confirmation: "password", address: "56 Jordan Avenue 3R, Jersey City, NJ 07306")
User.create(first_name: "Dominique", last_name: "Andre",password: "password", password_confirmation: "password")
User.create(first_name: "Donat", last_name: "Andre",password: "password", password_confirmation: "password", email: "donatandre@yahoo.com")
User.create(first_name: "Gertrude", last_name: "Andre",password: "password", password_confirmation: "password", email: "gertyandre@yahoo.fr")
User.create(first_name: "Kristie", last_name: "Barthelemy",password: "password", password_confirmation: "password")
User.create(first_name: "Catherine", last_name: "Beauboeuf",password: "password", password_confirmation: "password", email: "catherine.a.beauboeuf@gmail.com", address: "2 South Leavitt St unit 410, Chicago, Il 60612")
User.create(first_name: "Shanna", last_name: "Beauge",password: "password", password_confirmation: "password")
User.create(first_name: "Dupuis", last_name: "Bernado",password: "password", password_confirmation: "password")
User.create(first_name: "Soraya", last_name: "Blot",password: "password", password_confirmation: "password", address: "2867 Yonge Street Apt 2 Toronto ON M4N 2J5, Canada")
User.create(first_name: "Gary", last_name: "Brice",password: "password", password_confirmation: "password")
User.create(first_name: "Marthe", last_name: "Brice",password: "password", password_confirmation: "password")
User.create(first_name: "Stephan", last_name: "Brice",password: "password", password_confirmation: "password", email: "stephan.brice@gmail.com")
User.create(first_name: "Taina", last_name: "Brice",password: "password", password_confirmation: "password", email: "sweettay90@yahoo.fr")
User.create(first_name: "Adrienne", last_name: "Bus",password: "password", password_confirmation: "password")
User.create(first_name: "Carl-Henry", last_name: "Caidor",password: "password", password_confirmation: "password", email: "calhenry56@hotmail.com")
User.create(first_name: "Carole", last_name: "Caidor",password: "password", password_confirmation: "password", email: "jeanmaetcaro@gmail.com")
User.create(first_name: "Genevieve", last_name: "Caidor",password: "password", password_confirmation: "password", address: "14 Sterling Rd, Elmont, NY 11003")
User.create(first_name: "Jean-Marie", last_name: "Caidor",password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Marie Jr", last_name: "Caidor",password: "password", password_confirmation: "password", email: "jeanmariejr@gmail.com", address: "14 Sterling Rd, Elmont, NY 11003")
User.create(first_name: "Joan", last_name: "Caidor",password: "password", password_confirmation: "password")
User.create(first_name: "David", last_name: "Calixte",password: "password", password_confirmation: "password", email: "dcalixte2@gmail.com", address: "4702 Lake Park Pl, Acworth, GA 30101")
User.create(first_name: "Charles", last_name: "Carrenard",password: "password", password_confirmation: "password")
User.create(first_name: "Christian", last_name: "Carrenard",password: "password", password_confirmation: "password", address: "1137 E 100 St, Brooklyn NY 11236")
User.create(first_name: "Germaine", last_name: "Carrenard",password: "password", password_confirmation: "password")
User.create(first_name: "Herve", last_name: "Carrenard",password: "password", password_confirmation: "password", address: "1137 E 100 St, Brooklyn NY 11236")
User.create(first_name: "Sylvie", last_name: "Carrenard",password: "password", password_confirmation: "password", address: "1137 E 100 St, Brooklyn NY 11236")
User.create(first_name: "Tatianna", last_name: "Carrenard",password: "password", password_confirmation: "password", address: "1137 E 100 St, Brooklyn NY 11236")
User.create(first_name: "Jacoune", last_name: "Cayenne",password: "password", password_confirmation: "password")
User.create(first_name: "Minou", last_name: "Cayenne",password: "password", password_confirmation: "password")
User.create(first_name: "Pere Dume", last_name: "Cayenne",password: "password", password_confirmation: "password")
User.create(first_name: "Pere Jude", last_name: "Cayenne",password: "password", password_confirmation: "password")
User.create(first_name: "Pere Reginal", last_name: "Cayenne",password: "password", password_confirmation: "password")
User.create(first_name: "Jethro", last_name: "Celestin",password: "password", password_confirmation: "password", email: "timalis01@gmail.com")
User.create(first_name: "Dr. Marjorie", last_name: "Charles",password: "password", password_confirmation: "password")
User.create(first_name: "Dabel", last_name: "Dabel",password: "password", password_confirmation: "password")
User.create(first_name: "darline", last_name: "Darline",password: "password", password_confirmation: "password")
User.create(first_name: "Alyn", last_name: "Defay",password: "password", password_confirmation: "password", address: "115-71 223rd st Cambria heights, NY 11411")
User.create(first_name: "Fabrice", last_name: "Defay",password: "password", password_confirmation: "password", address: "115-71 223rd st Cambria heights, NY 11411")
User.create(first_name: "Jennifer", last_name: "Desir",password: "password", password_confirmation: "password", address: "480 NW 20th St. Apt 202. Boca Raton, Fl 33431")
User.create(first_name: "Metive", last_name: "Dieudonne",password: "password", password_confirmation: "password")
User.create(first_name: "Frances", last_name: "Dormethus",password: "password", password_confirmation: "password")
User.create(first_name: "Martine", last_name: "Dormethus",password: "password", password_confirmation: "password")
User.create(first_name: "Chrissie", last_name: "Dornevil",password: "password", password_confirmation: "password", address: "2780 Austin Ridge Drive, Dacula, Ga 30019")
User.create(first_name: "Alexa", last_name: "Dubois",password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Paul", last_name: "Duperval",password: "password", password_confirmation: "password", address: "93 Soundview Ave Bridgeport, CT 06606")
User.create(first_name: "Craig", last_name: "EUHHH",password: "password", password_confirmation: "password")
User.create(first_name: "Anne-Carine", last_name: "Exume",password: "password", password_confirmation: "password")
User.create(first_name: "Arthur", last_name: "Exume",password: "password", password_confirmation: "password", email: "arthurexume@gmail.com")
User.create(first_name: "Bertrand", last_name: "Exume",password: "password", password_confirmation: "password", email: "bigberty2001@hotmail.com")
User.create(first_name: "Christian", last_name: "Exume",password: "password", password_confirmation: "password")
User.create(first_name: "Claudine", last_name: "Exume",password: "password", password_confirmation: "password")
User.create(first_name: "Matthieu", last_name: "Exume",password: "password", password_confirmation: "password")
User.create(first_name: "Melissa", last_name: "Exume",password: "password", password_confirmation: "password", email: "melissa.exume@hotmail.com")
User.create(first_name: "Mireille", last_name: "Exume",password: "password", password_confirmation: "password", email: "rosemireillexume@gmail.com")
User.create(first_name: "Olivier", last_name: "Exume",password: "password", password_confirmation: "password")
User.create(first_name: "Christel", last_name: "Fenelon",password: "password", password_confirmation: "password")
User.create(first_name: "Aurelie", last_name: "Fievre",password: "password", password_confirmation: "password")
User.create(first_name: "Louckendia", last_name: "Francois",password: "password", password_confirmation: "password", address: "260 Rue Gamelin, Repentigny, QC J6A 5V1, Canada")
User.create(first_name: "Alfredo", last_name: "Frederique",password: "password", password_confirmation: "password")
User.create(first_name: "Cluvia", last_name: "Frederique",password: "password", password_confirmation: "password")
User.create(first_name: "Fred", last_name: "Frederique",password: "password", password_confirmation: "password")
User.create(first_name: "Lola", last_name: "Frederique",password: "password", password_confirmation: "password")
User.create(first_name: "Toto", last_name: "Frederique",password: "password", password_confirmation: "password")
User.create(first_name: "Roudy", last_name: "Gerlus",password: "password", password_confirmation: "password")
User.create(first_name: "Gigi", last_name: "Gigi",password: "password", password_confirmation: "password")
User.create(first_name: "David", last_name: "Gonzales",password: "password", password_confirmation: "password")
User.create(first_name: "Dayana", last_name: "Gonzales",password: "password", password_confirmation: "password")
User.create(first_name: "Mon oncle Napo", last_name: "Guadeloupe",password: "password", password_confirmation: "password")
User.create(first_name: "Patrick", last_name: "Guadeloupe",password: "password", password_confirmation: "password")
User.create(first_name: "Sylvie", last_name: "Guadeloupe",password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Luc", last_name: "Hamilton",password: "password", password_confirmation: "password", email: "loverboy_739@hotmail.com")
User.create(first_name: "parrain de Seby", last_name: "Hilaire",password: "password", password_confirmation: "password")
User.create(first_name: "Christina", last_name: "Jean",password: "password", password_confirmation: "password", email: "titina_jn@hotmail.com", address: "1896 NW 145th Terrace, Pembroke Pines, FL 33028")
User.create(first_name: "Vicenta", last_name: "Jean Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Yadine", last_name: "Jean Jacques",password: "password", password_confirmation: "password")
User.create(first_name: "Alta", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Bonel", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Carmelle", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Elza", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Ezebre", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Frenie", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Guerrier", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Hirame", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Joanna", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Joey", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Luco", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password", address: "2823 Oswego Street, North Bellmore, NY 11710")
User.create(first_name: "Marcus", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Marie", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Marinelle", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Nathalie", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Pashoue", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Roro", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Stephanie", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password", address: "19 Wyndham Court Nanuet, NY 10954")
User.create(first_name: "Vladimir", last_name: "Jean-Baptiste",password: "password", password_confirmation: "password")
User.create(first_name: "Anne-Marie", last_name: "Jean-Lor",password: "password", password_confirmation: "password")
User.create(first_name: "Madan Pino", last_name: "Jean-Louis",password: "password", password_confirmation: "password", address: "239 East 51St #3 Brooklyn NY 11203")
User.create(first_name: "Pino", last_name: "Jean-Louis",password: "password", password_confirmation: "password", address: "239 East 51St #3 Brooklyn NY 11203")
User.create(first_name: "Stephane", last_name: "Jean-Pierre",password: "password", password_confirmation: "password")
User.create(first_name: "Claude", last_name: "Jean-Poix",password: "password", password_confirmation: "password")
User.create(first_name: "Nicole", last_name: "Jean-Poix",password: "password", password_confirmation: "password")
User.create(first_name: "Rene", last_name: "Joseph",password: "password", password_confirmation: "password")
User.create(first_name: "Ti Maude", last_name: "Kill",password: "password", password_confirmation: "password")
User.create(first_name: "Olguin", last_name: "Laroche",password: "password", password_confirmation: "password")
User.create(first_name: "Christiane", last_name: "Lecorps",password: "password", password_confirmation: "password")
User.create(first_name: "Ermond", last_name: "Lecorps",password: "password", password_confirmation: "password")
User.create(first_name: "Joujou", last_name: "Lecorps",password: "password", password_confirmation: "password")
User.create(first_name: "Myriam", last_name: "Lecorps",password: "password", password_confirmation: "password")
User.create(first_name: "Nath", last_name: "Lecorps",password: "password", password_confirmation: "password")
User.create(first_name: "Natalie", last_name: "Lemaine",password: "password", password_confirmation: "password")
User.create(first_name: "Robert", last_name: "Lemaine",password: "password", password_confirmation: "password")
User.create(first_name: "Leslie", last_name: "Leslie",password: "password", password_confirmation: "password")
User.create(first_name: "Emmanuelle", last_name: "Louis",password: "password", password_confirmation: "password", email: "manoucheserge@yahoo.fr")
User.create(first_name: "Sarah", last_name: "Louis",password: "password", password_confirmation: "password", address: "4707 Ave L, Brooklyn, NY 11234")
User.create(first_name: "Sebastien", last_name: "Louis",password: "password", password_confirmation: "password")
User.create(first_name: "Serge", last_name: "Louis",password: "password", password_confirmation: "password", email: "sergelouis22@hotmail.com", address: "Rue Alfred Laurence Apt 4 #11615, Montreal, QC H1E 3L6")
User.create(first_name: "Sergine", last_name: "Louis",password: "password", password_confirmation: "password", email: "sergine.louis@gmail.com", address: "4707 Ave L, Brooklyn, NY 11234")
User.create(first_name: "Stephanie", last_name: "Louis",password: "password", password_confirmation: "password", email: "Stephanie.louis94@gmail.com", address: "4707 Ave L, Brooklyn, NY 11234")
User.create(first_name: "Tarah", last_name: "Louis",password: "password", password_confirmation: "password", address: "1373 Rue du Relais, Laval, QC H7Y 1W2, Canada")
User.create(first_name: "Thiery", last_name: "Louis",password: "password", password_confirmation: "password", address: "4707 Ave L, Brooklyn, NY 11234")
User.create(first_name: "Eunide", last_name: "Ma marraine",password: "password", password_confirmation: "password")
User.create(first_name: "Hilaire", last_name: "Maisonneuve",password: "password", password_confirmation: "password")
User.create(first_name: "Kendia", last_name: "Maisonneuve",password: "password", password_confirmation: "password")
User.create(first_name: "Elliot Desruisseaux", last_name: "Maitre",password: "password", password_confirmation: "password")
User.create(first_name: "Femme", last_name: "Maitre",password: "password", password_confirmation: "password")
User.create(first_name: "Regine", last_name: "Manmie",password: "password", password_confirmation: "password")
User.create(first_name: "Thom", last_name: "Manmie",password: "password", password_confirmation: "password")
User.create(first_name: "Mme Abner", last_name: "Marc",password: "password", password_confirmation: "password")
User.create(first_name: "Mononcle Abner", last_name: "Marc",password: "password", password_confirmation: "password")
User.create(first_name: "Jean", last_name: "Marcelin",password: "password", password_confirmation: "password")
User.create(first_name: "Miquette", last_name: "Marcelin",password: "password", password_confirmation: "password")
User.create(first_name: "Jean-Claude", last_name: "Massena",password: "password", password_confirmation: "password", address: "146 -19th 227th Street Springfield gardens NY 11413")
User.create(first_name: "KArina", last_name: "Massena",password: "password", password_confirmation: "password", address: "146 -19th 227th Street Springfield gardens NY 11413")
User.create(first_name: "Patricia", last_name: "Massena",password: "password", password_confirmation: "password", address: "146 -19th 227th Street Springfield gardens NY 11413")
User.create(first_name: "Cassandre", last_name: "Merger",password: "password", password_confirmation: "password")
User.create(first_name: "Lucita", last_name: "Merger",password: "password", password_confirmation: "password")
User.create(first_name: "Sergio", last_name: "Merger",password: "password", password_confirmation: "password", email: "Sergeamerger@gmail.com")
User.create(first_name: "Pascal", last_name: "Merveille",password: "password", password_confirmation: "password", address: "4250 Alafaya Trail Suite 212-250, Oviedo, FL 32765")
User.create(first_name: "Gregory", last_name: "Michel",password: "password", password_confirmation: "password")
User.create(first_name: "Zebledlo", last_name: "Michel",password: "password", password_confirmation: "password")
User.create(first_name: "Margareth", last_name: "Mon parrain",password: "password", password_confirmation: "password")
User.create(first_name: "Mon parrain", last_name: "Mon parrain",password: "password", password_confirmation: "password")
User.create(first_name: "Frederique", last_name: "Montas",password: "password", password_confirmation: "password")
User.create(first_name: "Kimberly", last_name: "Ncolas",password: "password", password_confirmation: "password", address: "740 G St, Lincoln NE 68508")
User.create(first_name: "Canes", last_name: "Nicolas",password: "password", password_confirmation: "password", address: "740 G St, Lincoln NE 68508")
User.create(first_name: "Kristel", last_name: "Paul",password: "password", password_confirmation: "password")
User.create(first_name: "Pablo", last_name: "Paul",password: "password", password_confirmation: "password")
User.create(first_name: "Carlos", last_name: "Pereryra",password: "password", password_confirmation: "password", email: "crpereyra1@gmail.com", address: "8 Perimeter Ctr. E. 2319 Atlanta, GA 30346")
User.create(first_name: "Charissa", last_name: "Pierre",password: "password", password_confirmation: "password", email: "charissou13@yahoo.fr", address: "3450 Jones Mill Rd #520, Norcross, GA 30092")
User.create(first_name: "Fabienne", last_name: "Pierre",password: "password", password_confirmation: "password")
User.create(first_name: "Alain", last_name: "Pierre-Pierre",password: "password", password_confirmation: "password", address: "144-44 41st ave, Apt 1h, Flushing NY 11355")
User.create(first_name: "Linda", last_name: "Pierrot",password: "password", password_confirmation: "password")
User.create(first_name: "Georgette", last_name: "Remy",password: "password", password_confirmation: "password")
User.create(first_name: "Paulette", last_name: "Rochefort",password: "password", password_confirmation: "password")
User.create(first_name: "Rochefort", last_name: "Rochefort",password: "password", password_confirmation: "password")
User.create(first_name: "Maria", last_name: "Roy",password: "password", password_confirmation: "password")
User.create(first_name: "Clemene", last_name: "Semenran",password: "password", password_confirmation: "password")
User.create(first_name: "Agla", last_name: "Senatus",password: "password", password_confirmation: "password")
User.create(first_name: "Alain", last_name: "Senatus",password: "password", password_confirmation: "password", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1")
User.create(first_name: "Dorothy", last_name: "Senatus",password: "password", password_confirmation: "password")
User.create(first_name: "Fabrice", last_name: "Senatus",password: "password", password_confirmation: "password", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1")
User.create(first_name: "Larissa", last_name: "Senatus",password: "password", password_confirmation: "password", email: "slarissa90@hotmail.com")
User.create(first_name: "Luc", last_name: "Senatus",password: "password", password_confirmation: "password", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1")
User.create(first_name: "Mycotte", last_name: "Senatus",password: "password", password_confirmation: "password", address: "3990 Latour, Saint-Hubert, QC J3Y-4W1")
User.create(first_name: "Myriam", last_name: "Senatus",password: "password", password_confirmation: "password", email: "myraymi@yahoo.fr")
User.create(first_name: "Reyina", last_name: "Senatus",password: "password", password_confirmation: "password", address: "419 Towerview Drive - Box 98893, Edens 1A - Room 403, Durham, NC 27708")
User.create(first_name: "Ronald", last_name: "Senatus",password: "password", password_confirmation: "password", address: "2111 Branywine Rd Apt 913, West Palm beach FL 33409")
User.create(first_name: "Arabel", last_name: "Severe",password: "password", password_confirmation: "password", email: "arabel.severe94@gmail.com", address: "5332 Rpcking Horse Place Oviedo FL 32765")
User.create(first_name: "Chanel", last_name: "Smith",password: "password", password_confirmation: "password", address: "P.O. Box 881411, San Diego, California 92168")
User.create(first_name: "Altagrace", last_name: "Soeur",password: "password", password_confirmation: "password")
User.create(first_name: "Flor", last_name: "Soeur",password: "password", password_confirmation: "password")
User.create(first_name: "Franklin", last_name: "St-Surin",password: "password", password_confirmation: "password")
User.create(first_name: "Hans-Muller", last_name: "Thomas",password: "password", password_confirmation: "password", email: "hansmullerthomas@gmail.com")
User.create(first_name: "Kervens", last_name: "Thomas",password: "password", password_confirmation: "password", email: "tikikthomas@gmail.com")
User.create(first_name: "Nadine", last_name: "Thomas",password: "password", password_confirmation: "password", email: "dinoue03@yahoo.com")
User.create(first_name: "Sarah", last_name: "Thomas",password: "password", password_confirmation: "password", email: "tisasthomas@homail.com")
User.create(first_name: "Tibel", last_name: "Tibel",password: "password", password_confirmation: "password")
User.create(first_name: "Navneet", last_name: "Tiwari",password: "password", password_confirmation: "password", email: "er.navneettiwari@gmail.com", address: "425 Washingtn BLV Apt 3308 Jersey City NY07310")
User.create(first_name: "Francois", last_name: "Andre",password: "password", password_confirmation: "password", address: "397 East 7 St, Brooklyn, NY 11218")
User.create(first_name: "Ernst", last_name: "Toussaint",password: "password", password_confirmation: "password")
User.create(first_name: "Hilaire", last_name: "Toussaint",password: "password", password_confirmation: "password")
User.create(first_name: "Janette", last_name: "Toussaint",password: "password", password_confirmation: "password")
User.create(first_name: "Gheriane", last_name: "Ulysse",password: "password", password_confirmation: "password", address: "247 Crystal Downs Way, Suwanee GA 30024")
User.create(first_name: "Andy", last_name: "Valles",password: "password", password_confirmation: "password")
User.create(first_name: "Aurelie", last_name: "Valles",password: "password", password_confirmation: "password")
User.create(first_name: "Cassandra", last_name: "Valles",password: "password", password_confirmation: "password", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada")
User.create(first_name: "Chantale", last_name: "Valles",password: "password", password_confirmation: "password", email: "chantale24@yahoo.com", address: "1746 Woodwalk Creek, Atlanta, GA, 30339")
User.create(first_name: "Dominique", last_name: "Valles",password: "password", password_confirmation: "password", address: "2272 Norbury Dr, Smyrna, GA 30080")
User.create(first_name: "Eunide", last_name: "Valles",password: "password", password_confirmation: "password", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada")
User.create(first_name: "Gaelle", last_name: "Valles",password: "password", password_confirmation: "password", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada")
User.create(first_name: "Jude", last_name: "Valles",password: "password", password_confirmation: "password", email: "judevalles16@yahoo.com", address: "2272 Norbury Dr, Smyrna, GA 30080")
User.create(first_name: "Lyonel", last_name: "Valles",password: "password", password_confirmation: "password", email: "lyonel.valles@yahoo.com", address: "570 Rue Valois, Laval, QC H7M 1S5, Canada")
User.create(first_name: "Nadege", last_name: "Valles",password: "password", password_confirmation: "password", address: "2272 Norbury Dr, Smyrna, GA 30080")
User.create(first_name: "Phillip", last_name: "Valles",password: "password", password_confirmation: "password", address: "2272 Norbury Dr, Smyrna, GA 30080")
User.create(first_name: "Annaise", last_name: "Verret",password: "password", password_confirmation: "password", email: "raphaelle.verret@gmail.com", address: "4250 Alafaya Trail Suite 212-250, Oviedo, FL 32765")
User.create(first_name: "Ericson", last_name: "Vibert",password: "password", password_confirmation: "password", address: "1049 powers ferry rd apt 203 Marietta GA 30067")
User.create(first_name: "Joanne", last_name: "Voisine",password: "password", password_confirmation: "password")
User.create(first_name: "Katie", last_name: "Weander",password: "password", password_confirmation: "password", email: "katie_weander@hotmail.com", address: "17734 Castelar Cir, Omaha NE 6810")
User.create(first_name: "Femme", last_name: "Wesner",password: "password", password_confirmation: "password")
User.create(first_name: "Marc", last_name: "Wesner",password: "password", password_confirmation: "password")
User.create(first_name: "Bugra", last_name: "Yavuz",password: "password", password_confirmation: "password", email: "bugrahanyavuz@gmail.com")

#49.times do |n|
#  first_name  = Faker::Name.first_name
#  last_name  = Faker::Name.last_name
#  email = "example-#{n+1}@dummy.org"
#  password = "password"
#  User.create!(first_name:  first_name,
#  			   last_name:  last_name,
#               email: email,
#               password: password,
#               password_confirmation: password)
#end